//go:build !ignore_autogenerated

/*
Copyright 2025 Zera Holladay.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GSMSecret) DeepCopyInto(out *GSMSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GSMSecret.
func (in *GSMSecret) DeepCopy() *GSMSecret {
	if in == nil {
		return nil
	}
	out := new(GSMSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GSMSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GSMSecretEntry) DeepCopyInto(out *GSMSecretEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GSMSecretEntry.
func (in *GSMSecretEntry) DeepCopy() *GSMSecretEntry {
	if in == nil {
		return nil
	}
	out := new(GSMSecretEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GSMSecretList) DeepCopyInto(out *GSMSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GSMSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GSMSecretList.
func (in *GSMSecretList) DeepCopy() *GSMSecretList {
	if in == nil {
		return nil
	}
	out := new(GSMSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GSMSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GSMSecretSpec) DeepCopyInto(out *GSMSecretSpec) {
	*out = *in
	out.TargetSecret = in.TargetSecret
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]GSMSecretEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GSMSecretSpec.
func (in *GSMSecretSpec) DeepCopy() *GSMSecretSpec {
	if in == nil {
		return nil
	}
	out := new(GSMSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GSMSecretStatus) DeepCopyInto(out *GSMSecretStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GSMSecretStatus.
func (in *GSMSecretStatus) DeepCopy() *GSMSecretStatus {
	if in == nil {
		return nil
	}
	out := new(GSMSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GSMSecretTargetSecret) DeepCopyInto(out *GSMSecretTargetSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GSMSecretTargetSecret.
func (in *GSMSecretTargetSecret) DeepCopy() *GSMSecretTargetSecret {
	if in == nil {
		return nil
	}
	out := new(GSMSecretTargetSecret)
	in.DeepCopyInto(out)
	return out
}
